### ISSUE TITLE
relaxing bounds

### ISSUE THREAD

**Issue by juhp** [bcardiff/haskell-tinyapp#1]
Cool little project thanks - I like it.

Would you be open to relaxing the bounds, which are really quite strict now.

I managed to build it using Stackage nightly, lts 22, 21 and 20 (which has brick 5 for instance).
I can open a PR for it. That would make it rather easier also for others to build.

**Comment by bcardiff** [comment]
Hi! Sure, send the PR. I don't use stack.

I'm teaching a Haskell course and wanted a simpler interface for these kind of apps

**Comment by bcardiff** [comment]
I checked with latest hackage index and ghc and with the pushed relaxed bounds the example works with brick 2.5

I sent a new revision to hackage already.

If this doesn't unblock what you want to do, let me know.
